#!/bin/bash

/usr/sbin/groupadd gwusers > /dev/null 2> /dev/null
/usr/sbin/useradd -d /usr/share/gridway -g gwusers -s /bin/sh gwadmin > /dev/null 2> /dev/null
chown -R gwadmin:gwusers /usr/share/gridway/5.10.0
/sbin/chkconfig --add gridway-core
/sbin/ldconfig
