#!/bin/bash

echo "# MADs for OGSA-BES
IM_MAD = static:gw_im_mad_static:-l etc/BES_hosts.list:dummy:bes
EM_MAD = bes:GW_em_mad_bes::jsdl
TM_MAD = dummy:gw_tm_mad_dummy:-u gsiftp\://<hostname>" >> /usr/etc/gwd.conf

touch /usr/etc/BES_hosts.list
