#!/bin/bash

sed '/# MADs for OGSA-BES/d' -i /usr/etc/gwd.conf
sed '/bes/d' -i /usr/etc/gwd.conf
sed '/dummy/d' -i /usr/etc/gwd.conf
if [ ! -s "/usr/etc/BES_hosts.list" ]; then
 rm -f /usr/etc/BES_hosts.list;
fi
