#line 2 "src/gwd/gw_conf_parser.c"

#line 4 "src/gwd/gw_conf_parser.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gcp_restart(gcp_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int gcp_leng;

extern FILE *gcp_in, *gcp_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE gcp_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-gcp_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < gcp_leng; ++yyl )\
                    if ( gcp_text[yyl] == '\n' )\
                        --gcp_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gcp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gcp_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gcp_restart()), so that the user can continue scanning by
	 * just pointing gcp_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gcp_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int gcp_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gcp_wrap()'s to do buffer switches
 * instead of setting up a fresh gcp_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gcp_restart (FILE *input_file  );
void gcp__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gcp__create_buffer (FILE *file,int size  );
void gcp__delete_buffer (YY_BUFFER_STATE b  );
void gcp__flush_buffer (YY_BUFFER_STATE b  );
void gcp_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gcp_pop_buffer_state (void );

static void gcp_ensure_buffer_stack (void );
static void gcp__load_buffer_state (void );
static void gcp__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gcp__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gcp__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gcp__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gcp__scan_bytes (yyconst char *bytes,int len  );

void *gcp_alloc (yy_size_t  );
void *gcp_realloc (void *,yy_size_t  );
void gcp_free (void *  );

#define yy_new_buffer gcp__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gcp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gcp__create_buffer(gcp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gcp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gcp__create_buffer(gcp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *gcp_in = (FILE *) 0, *gcp_out = (FILE *) 0;

typedef int yy_state_type;

extern int gcp_lineno;

int gcp_lineno = 1;

extern char *gcp_text;
#define yytext_ptr gcp_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gcp_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	gcp_leng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[227] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,   23,   26,   26,   31,   28,   27,   27,   29,   29,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   30,
       30,   16,   30,   17,   30,   18,   30,   19,   30,   20,
       23,   23,   21,   23,   22,   26,   26,   24,   26,   25,
       28,   27,    0,    1,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,    0,   16,   16,    0,   17,
       17,    0,   18,   18,    0,   19,    0,    0,   20,   23,
       22,   23,   21,   23,   23,   22,   26,   26,   24,   26,
       26,    0,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,    0,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   14,   28,
       12,   28,   28,   28,   28,   28,   13,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   15,    2,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       11,   28,   28,   28,   28,   28,   28,    5,   28,   28,

       28,   28,   28,   28,    6,    7,   28,   28,   28,   28,
        4,   28,   28,   28,   28,   28,    9,   28,   28,   28,
       28,   10,    8,   28,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    1,    1,
        7,    1,    1,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,    1,   18,   19,   20,   21,   22,
        1,   23,   24,   25,   26,   27,   28,   29,   30,    1,
        1,    1,    1,    1,   31,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[32] =
    {   0,
        1,    2,    3,    2,    1,    4,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[239] =
    {   0,
        0,    0,   30,   31,   32,   33,   34,   40,   41,   46,
       50,   55,   60,   65,  325,    0,   70,   72,  321,  326,
       60,  304,  294,  302,   57,  294,  298,  308,  298,  326,
       53,  314,   75,  313,   78,  312,   84,  326,  310,  307,
      305,   87,  326,   78,  326,    0,   92,  326,   94,  326,
        0,   96,  307,  326,  285,  277,  276,  295,  274,  275,
      283,  283,  283,  285,  268,   99,  296,  295,  100,  294,
      293,  101,  292,  291,  107,  326,  289,  288,  285,  283,
      326,  110,  326,  112,  114,  285,    0,  119,  326,  121,
      122,  284,  276,  261,  265,  252,  263,  250,  264,  270,

      260,  265,  257,  272,  253,  263,  264,  249,  262,  249,
      243,  255,  235,  254,  256,  236,  247,  250,  239,  248,
      232,  236,  233,  239,  228,  242,  240,  239,    0,  227,
        0,  230,  225,  216,  226,  227,    0,  221,  232,  217,
      232,  224,  218,  213,  221,  206,    0,    0,  223,  214,
      220,  220,  211,  199,  206,  214,  196,  203,  211,  208,
      192,  191,  118,  194,  189,  199,  197,  201,  193,  194,
      193,  189,  204,  195,  185,  196,  188,  184,  182,  196,
      192,  185,  182,  189,  169,  174,  190,  172,  172,  172,
        0,  169,  170,  182,  179,  141,  135,    0,  134,  131,

      115,  123,  117,  115,    0,    0,  115,  129,  120,  107,
        0,  105,  113,  118,  121,  111,    0,   85,   86,   74,
       58,    0,    0,   46,    0,  326,  144,  148,  152,  156,
      160,  164,  168,  172,  176,  178,  182,  186
    } ;

static yyconst flex_int16_t yy_def[239] =
    {   0,
      226,    1,  227,  227,  227,  227,  227,  227,  227,  227,
      228,  228,  229,  229,  226,  230,  226,  226,  231,  226,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  232,  226,
      233,  233,  226,  234,  226,  235,  235,  226,  236,  226,
      230,  226,  231,  226,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  232,  232,  226,  233,
      226,  233,  226,  234,  234,  237,  235,  235,  226,  236,
      236,  238,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  237,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,    0,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226
    } ;

static yyconst flex_int16_t yy_nxt[358] =
    {   0,
       16,   17,   18,   19,   16,   16,   20,   16,   16,   16,
       21,   22,   16,   23,   16,   24,   16,   16,   25,   26,
       16,   27,   16,   28,   29,   16,   16,   16,   16,   16,
       16,   31,   31,   33,   33,   35,   32,   32,   34,   34,
       36,   35,   37,   38,   39,   40,   36,   37,   38,   39,
       40,   42,   43,   44,   66,   45,   42,   43,   44,   67,
       45,   47,   48,   49,   60,   50,   47,   48,   49,  225,
       50,   52,   52,   52,   52,   55,   69,   61,   56,   72,
       83,   70,  224,   86,   73,   75,   76,   77,   82,   83,
       84,  223,   81,   88,   89,   90,   89,   52,   52,   92,

       66,   69,   72,  222,  221,   67,   70,   73,   75,   76,
       77,   82,   83,   84,   83,   81,   83,   86,  220,   86,
       88,   89,   90,   89,   89,  169,   92,   92,  219,  218,
      217,  216,  170,  215,  171,  214,  213,  212,  211,  210,
      209,  208,  207,  172,   30,   30,   30,   30,   41,   41,
       41,   41,   46,   46,   46,   46,   51,  206,  205,   51,
       53,   53,   53,   53,   78,   78,   78,   78,   80,   80,
      204,   80,   85,   85,   85,   85,   87,   87,   91,   91,
       91,   91,  104,  104,  104,  104,   92,   92,   92,   92,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,

      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  118,  117,  116,   83,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,   89,   83,   81,   79,
       76,   76,   74,   74,   71,   71,   68,   68,  103,  102,

      101,  100,   99,   98,   97,   96,   95,   94,   93,   54,
       81,   79,   76,   74,   71,   68,   65,   64,   63,   62,
       59,   58,   57,   54,  226,   15,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226
    } ;

static yyconst flex_int16_t yy_chk[358] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    7,    3,    4,    5,    6,
        7,    8,    9,    9,    9,    9,    8,   10,   10,   10,
       10,   11,   11,   11,   31,   11,   12,   12,   12,   31,
       12,   13,   13,   13,   25,   13,   14,   14,   14,  224,
       14,   17,   17,   18,   18,   21,   33,   25,   21,   35,
       44,   33,  221,   44,   35,   37,   37,   37,   42,   42,
       42,  220,   42,   47,   47,   47,   49,   52,   52,   49,

       66,   69,   72,  219,  218,   66,   69,   72,   75,   75,
       75,   82,   82,   82,   84,   82,   85,   84,  216,   85,
       88,   88,   88,   90,   91,  163,   90,   91,  215,  214,
      213,  212,  163,  210,  163,  209,  208,  207,  204,  203,
      202,  201,  200,  163,  227,  227,  227,  227,  228,  228,
      228,  228,  229,  229,  229,  229,  230,  199,  197,  230,
      231,  231,  231,  231,  232,  232,  232,  232,  233,  233,
      196,  233,  234,  234,  234,  234,  235,  235,  236,  236,
      236,  236,  237,  237,  237,  237,  238,  238,  238,  238,
      195,  194,  193,  192,  190,  189,  188,  187,  186,  185,

      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  136,  135,  134,  133,  132,  130,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   86,   80,   79,
       78,   77,   74,   73,   71,   70,   68,   67,   65,   64,

       63,   62,   61,   60,   59,   58,   57,   56,   55,   53,
       41,   40,   39,   36,   34,   32,   29,   28,   27,   26,
       24,   23,   22,   19,   15,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[31] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int gcp__flex_debug;
int gcp__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *gcp_text;
#line 1 "src/gwd/gw_conf_parser.l"
/* -------------------------------------------------------------------------- */
/* Copyright 2002-2006 GridWay Team, Distributed Systems Architecture         */
/* Group, Universidad Complutense de Madrid                                   */
/*                                                                            */
/* Licensed under the Apache License, Version 2.0 (the "License"); you may    */
/* not use this file except in compliance with the License. You may obtain    */
/* a copy of the License at                                                   */
/*                                                                            */
/* http://www.apache.org/licenses/LICENSE-2.0                                 */
/*                                                                            */
/* Unless required by applicable law or agreed to in writing, software        */
/* distributed under the License is distributed on an "AS IS" BASIS,          */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   */
/* See the License for the specific language governing permissions and        */
/* limitations under the License.                                             */
/* -------------------------------------------------------------------------- */
#line 19 "src/gwd/gw_conf_parser.l"
#include <stdio.h>
#include <string.h>
#include "gw_conf.h"
#include "gw_log.h"
#define STR_SIZE 512
#define YY_DECL static int yylex_gwd_conf()

void gcp_set_val_int(gw_conf_var_t var, int val);
void init_mad_parser(int mad_index);
void process_escaped_chars(char *str);

char ***gcp_mads;

gw_conf_var_t gcp_var;

int  gcp_i,gcp_j;
int  gcp_num  = 0;
int  gcp_max;







#line 671 "src/gwd/gw_conf_parser.c"

#define INITIAL 0
#define var_int 1
#define var_mad 2
#define var_sch 3
#define val_int 4
#define val_mad 5
#define val_sch 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gcp_wrap (void );
#else
extern int gcp_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( gcp_text, gcp_leng, 1, gcp_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gcp_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gcp_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gcp_in))==0 && ferror(gcp_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gcp_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gcp_lex (void);

#define YY_DECL int gcp_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gcp_text and gcp_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 50 "src/gwd/gw_conf_parser.l"


    /* --------------------------------------------------------------------- */
    /*    Parse comments                                                     */
    /* --------------------------------------------------------------------- */
    
#line 835 "src/gwd/gw_conf_parser.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gcp_in )
			gcp_in = stdin;

		if ( ! gcp_out )
			gcp_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gcp_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gcp__create_buffer(gcp_in,YY_BUF_SIZE );
		}

		gcp__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of gcp_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 227 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 326 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < gcp_leng; ++yyl )
				if ( gcp_text[yyl] == '\n' )
					   
    gcp_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 56 "src/gwd/gw_conf_parser.l"
;
	YY_BREAK
/* --------------------------------------------------------------------- */
/*    Variable Parsing                                                   */
/* --------------------------------------------------------------------- */
case 2:
YY_RULE_SETUP
#line 62 "src/gwd/gw_conf_parser.l"
{ gcp_var = GWD_PORT;              BEGIN var_int;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "src/gwd/gw_conf_parser.l"
{ gcp_var = MAX_NUMBER_OF_CLIENTS; BEGIN var_int;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "src/gwd/gw_conf_parser.l"
{ gcp_var = NUMBER_OF_ARRAYS;      BEGIN var_int;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "src/gwd/gw_conf_parser.l"
{ gcp_var = NUMBER_OF_JOBS;        BEGIN var_int;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "src/gwd/gw_conf_parser.l"
{ gcp_var = NUMBER_OF_HOSTS;       BEGIN var_int;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "src/gwd/gw_conf_parser.l"
{ gcp_var = NUMBER_OF_USERS;       BEGIN var_int;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "src/gwd/gw_conf_parser.l"
{ gcp_var = SCHEDULING_INTERVAL;   BEGIN var_int;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "src/gwd/gw_conf_parser.l"
{ gcp_var = DISCOVERY_INTERVAL;    BEGIN var_int;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "src/gwd/gw_conf_parser.l"
{ gcp_var = MONITORING_INTERVAL;   BEGIN var_int;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "src/gwd/gw_conf_parser.l"
{ gcp_var = POLL_INTERVAL;         BEGIN var_int;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "src/gwd/gw_conf_parser.l"
{ gcp_var = IM_MAD; init_mad_parser(0); BEGIN var_mad;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "src/gwd/gw_conf_parser.l"
{ gcp_var = TM_MAD; init_mad_parser(1); BEGIN var_mad;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "src/gwd/gw_conf_parser.l"
{ gcp_var = EM_MAD; init_mad_parser(2); BEGIN var_mad;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "src/gwd/gw_conf_parser.l"
{ gcp_var = DM_SCHED; gcp_j = 0;   BEGIN var_sch;}
	YY_BREAK
/* --------------------------------------------------------------------- */
/*    Assignment Parsing                                                 */
/* --------------------------------------------------------------------- */
case 16:
YY_RULE_SETUP
#line 81 "src/gwd/gw_conf_parser.l"
{ BEGIN val_int;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "src/gwd/gw_conf_parser.l"
{ BEGIN val_mad;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "src/gwd/gw_conf_parser.l"
{ BEGIN val_sch;}
	YY_BREAK
/* --------------------------------------------------------------------- */
/*    Value Parsing                                                      */
/* --------------------------------------------------------------------- */
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 89 "src/gwd/gw_conf_parser.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "src/gwd/gw_conf_parser.l"
{ gcp_set_val_int(gcp_var, atoi(gcp_text));}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 92 "src/gwd/gw_conf_parser.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "src/gwd/gw_conf_parser.l"
{ if ( gcp_text[gcp_leng-2] == '\\' )
                          {
                            yymore();
                          }
                          else
                          {
                            if ( gcp_mads != NULL )
                            {
                                gcp_text[gcp_leng-1] = '\0';
                                process_escaped_chars(gcp_text);
                                gcp_mads[gcp_num][gcp_j] = strdup(gcp_text);
                            }
                            gcp_j++;
                            if (gcp_j >= gcp_max)
                            {
                                gw_log_print("GW",'E',"gwd.conf: Parse error in MAD at line %i\n", gcp_lineno);
                                return -1;
                            }
                          }
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 113 "src/gwd/gw_conf_parser.l"
{ if ( gcp_mads != NULL )
                          {
                            process_escaped_chars(gcp_text);
                            gcp_mads[gcp_num][gcp_j] = strdup(gcp_text);
                          }
                        }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 120 "src/gwd/gw_conf_parser.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 121 "src/gwd/gw_conf_parser.l"
{ gcp_j++;
                          if (gcp_j >= 3)
                          {
                              gw_log_print("GW",'E',"gwd.conf: Parse error in Sched at line %i\n", gcp_lineno);
                              return -1;
                          }
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "src/gwd/gw_conf_parser.l"
{ gw_conf.dm_mad[gcp_j] = strdup(gcp_text);}
	YY_BREAK
/* --------------------------------------------------------------------- */
/*    Default Parsing                                                    */
/* --------------------------------------------------------------------- */
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 134 "src/gwd/gw_conf_parser.l"
;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 135 "src/gwd/gw_conf_parser.l"
{ gw_log_print("GW",'E',"Undefined variable (%s) at line %i\n",
                        gcp_text, gcp_lineno);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 138 "src/gwd/gw_conf_parser.l"
{ gw_log_print("GW",'E',"gwd.conf: Parse error at line %i\n",gcp_lineno);
                  return -1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 140 "src/gwd/gw_conf_parser.l"
ECHO;
	YY_BREAK
#line 1133 "src/gwd/gw_conf_parser.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(var_int):
case YY_STATE_EOF(var_mad):
case YY_STATE_EOF(var_sch):
case YY_STATE_EOF(val_int):
case YY_STATE_EOF(val_mad):
case YY_STATE_EOF(val_sch):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gcp_in at a new source and called
			 * gcp_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gcp_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gcp_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gcp_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of gcp_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					gcp_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gcp_restart(gcp_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 227 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 227 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 226);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gcp_restart(gcp_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gcp_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gcp_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    gcp_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gcp_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gcp_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gcp__create_buffer(gcp_in,YY_BUF_SIZE );
	}

	gcp__init_buffer(YY_CURRENT_BUFFER,input_file );
	gcp__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gcp__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gcp_pop_buffer_state();
	 *		gcp_push_buffer_state(new_buffer);
     */
	gcp_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gcp__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gcp_wrap()) processing, but the only time this flag
	 * is looked at is after gcp_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gcp__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gcp_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gcp__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gcp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gcp__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gcp_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gcp__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gcp__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gcp__create_buffer()
 * 
 */
    void gcp__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gcp_free((void *) b->yy_ch_buf  );

	gcp_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gcp_restart() or at EOF.
 */
    static void gcp__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gcp__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gcp__init_buffer was _probably_
     * called from gcp_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gcp__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gcp__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gcp_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gcp_ensure_buffer_stack();

	/* This block is copied from gcp__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gcp__switch_to_buffer. */
	gcp__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gcp_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gcp__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gcp__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gcp_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)gcp_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gcp_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gcp__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gcp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gcp__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gcp__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gcp_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gcp__scan_bytes() instead.
 */
YY_BUFFER_STATE gcp__scan_string (yyconst char * yystr )
{
    
	return gcp__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gcp_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gcp__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gcp_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gcp__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gcp__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gcp__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gcp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gcp_text[gcp_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gcp_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gcp_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gcp_get_lineno  (void)
{
        
    return gcp_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gcp_get_in  (void)
{
        return gcp_in;
}

/** Get the output stream.
 * 
 */
FILE *gcp_get_out  (void)
{
        return gcp_out;
}

/** Get the length of the current token.
 * 
 */
int gcp_get_leng  (void)
{
        return gcp_leng;
}

/** Get the current token.
 * 
 */

char *gcp_get_text  (void)
{
        return gcp_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void gcp_set_lineno (int  line_number )
{
    
    gcp_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see gcp__switch_to_buffer
 */
void gcp_set_in (FILE *  in_str )
{
        gcp_in = in_str ;
}

void gcp_set_out (FILE *  out_str )
{
        gcp_out = out_str ;
}

int gcp_get_debug  (void)
{
        return gcp__flex_debug;
}

void gcp_set_debug (int  bdebug )
{
        gcp__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gcp_lex_destroy(), so don't allocate here.
     */

    /* We do not touch gcp_lineno unless the option is enabled. */
    gcp_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    gcp_in = stdin;
    gcp_out = stdout;
#else
    gcp_in = (FILE *) 0;
    gcp_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gcp_lex_init()
     */
    return 0;
}

/* gcp_lex_destroy is for both reentrant and non-reentrant scanners. */
int gcp_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gcp__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gcp_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gcp_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gcp_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gcp_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *gcp_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gcp_free (void * ptr )
{
	free( (char *) ptr );	/* see gcp_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 140 "src/gwd/gw_conf_parser.l"



void gcp_set_val_int(gw_conf_var_t var, int val)
{
    switch(var)
    {
        case DISCOVERY_INTERVAL:
            gw_conf.discovery_interval = val;
            break;
            
        case GWD_PORT:
            gw_conf.gwd_port = val;
            break;

        case MONITORING_INTERVAL:
            gw_conf.monitoring_interval = val;
            break;        

        case MAX_NUMBER_OF_CLIENTS:
            gw_conf.max_number_of_clients = val;
            break;        
        
        case NUMBER_OF_ARRAYS:
            gw_conf.number_of_arrays = val;
            break;

        case NUMBER_OF_JOBS:
            gw_conf.number_of_jobs = val;
            break;

        case NUMBER_OF_HOSTS:
            gw_conf.number_of_hosts = val;
            break;

        case NUMBER_OF_USERS:
            gw_conf.number_of_users = val;
            break;
            		
		case POLL_INTERVAL:
			gw_conf.poll_interval = val;
			break;
			
		case SCHEDULING_INTERVAL:
			gw_conf.scheduling_interval = val;
			break;		

		default:
            gw_log_print("GW",'E',"Error! Unknown variable\n");
			break;
    }
}

void init_mad_parser(int mad_index)
{
	gcp_j = 0;
	
	switch (mad_index)
	{
		case 0:
			gcp_mads = gw_conf.im_mads;
            gcp_max  = 6;
			break;
			
		case 1:
			gcp_mads = gw_conf.tm_mads;
            gcp_max  = 3;
			break;
            
		case 2:
			gcp_mads = gw_conf.em_mads;
            gcp_max  = 3;
			break;
			
		default:
	        gw_log_print("GW",'E',"gwd.conf: Unexpected error parsing MAD, line %i\n",gcp_lineno);
	        break;	
	}
	
	gcp_num = 0;
	
	while ( gcp_mads[gcp_num][0] != NULL )
	{
	    gcp_num++;
	    if ( gcp_num == GW_MAX_MADS )
        {
            gw_log_print("GW",'W',"gwd.conf: Max. number of MAD reached, ignoring MAD, line %i\n",gcp_lineno);
            gcp_mads = NULL;
        }
    }
    
}

void process_escaped_chars(char *str)
{
    int i, j;
    
    for (i = 0, j = 0; str[i] != '\0'; i++)
    {
        if ( str[i] != '\\' )
            str[j++] = str[i];
    }
    
    str[j] = '\0';
}

int gcp_wrap(void)
{
    return 1;
}

int gw_conf_lex_parser ()
{
    int rc;
	
    gw_log_print("GW",'I',"gwd.conf: Loading configuration, file %s\n",gw_conf.conf_file);
    
    gcp_lineno = 0;
    gcp_in = fopen (gw_conf.conf_file,"r");

    if (gcp_in == NULL)
    {
        gw_log_print("GW",'E',"gwd.conf: Error opening file\n"); 
        fprintf(stderr,"Error opening gwd.conf file (%s)\n",gw_conf.conf_file);
        return -1;
    }
    
    rc = yylex_gwd_conf();
    
    fclose(gcp_in);
    
    return rc;
}

